{{- if .Values.secretMessage.create -}}
apiVersion: v1
kind: Secret
namespace: python-app
metadata:
  name: {{ include "project-helm-argocd.fullname" . }}-secret
type: Opaque
data:
  MENSAJE: {{ .Values.secretMessage.message | b64enc | quote }}
{{- end }}